DROP TABLE IF EXISTS `order`;

CREATE TABLE `order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(24) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

-- INSERT INTO `order` VALUES (1, 'PROCESSING', '2025-02-04 17:00:00');
-- INSERT INTO `order` VALUES (2, 'PROCESSED');

SELECT * FROM possystem.order;